smpl @all

'Variables AGALPVEH AGASGALM AMPG AUTOPR AUTOPRICE05 AVEH AVMTM AVMTPVEH C CPI2005 DEMOG GASPR05 GDPB2005 POPK RESID TOTGASCLM TOTGASGALPVEH TOTMPG TOTVEH TOTVMTM TOTVMTPVEH YR 



GENR GDPB05 = GDPB2005 

GENR AGASGALMCAP = AGASGALM/POPK 

GENR TOTGASGALMCP = AGASGALM/POPK

GENR AVEHCAP= AVEH/POPK

GENR TOTVEHCAP= TOTVEH/POPK

GENR GDP05CAP = GDPB2005/POPK

GENR AVMTMCAP = AVMTM/POPK 

GENR TOTVMTMCAP= TOTVMTM/POPK





for %1 AGALPVEH AGASGALM AMPG AUTOPR AUTOPRICE05 AVEH AVMTM AVMTPVEH CPI2005 GASPR05 GDPB2005 GDPB05 POPK TOTGASCLM TOTGASGALPVEH TOTMPG TOTVEH TOTVMTM TOTVMTMCAP TOTVMTPVEH AGASGALMCAP TOTGASGALMCP AVEHCAP TOTVEHCAP GDP05CAP AVMTMCAP AVMTMCAP 

genr L{%1}=log({%1})

genr d{%1}=L{%1}-L{%1}(-1)

next

GENR LYR=log(YR)



SMPL 1946 2010

VAR XVARAUTO.LS 1 4 DAVMTMCAP DAMPG DAVEHCAP @ C DEMOG DGDP05CAP DGASPR05



VAR XVARALLVEH.LS 1 4 DTOTVMTMCAP DTOTMPG DTOTVEHCAP @ C DEMOG DGDP05CAP DGASPR05



VAR XVARALLVEH2.LS 1 4 DTOTVMTMCAP DTOTMPG DTOTVEHCAP @ C DGDP05CAP DGASPR05



